### ISSUE TITLE
Error while setting up sengledapi platform for light [Bug]

### ISSUE THREAD

**Issue by mitchellross** [jfarmer08/ha-sengledapi#3] opened 2020-06-16 12:58 UTC
I've got it to log in - but I'm getting this error:

2020-06-16 22:54:22 ERROR (MainThread) [homeassistant.components.light] Error while setting up sengledapi platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 178, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/sengledapi_old/light.py", line 33, in async_setup_platform
    for light in await hass.data[DOMAIN]["sengledapi_account"].async_list_bulbs()
  File "/config/custom_components/sengledapi_old/sengledapi/sengledapi.py", line 86, in async_list_bulbs
    device["attributes"]["brightness"],
KeyError: 'brightness'

**Comment by jfarmer08** [comment] 2020-06-16 16:30
Can you turn on logging? 
```
logger:
  default: warning
  logs:
    custom_components.sengledapi: debug
```

**Comment by mitchellross** [comment] 2020-06-16 23:18
Yes I have done so and can share the full log. Which bits should I remove before sharing publically?

**Comment by jfarmer08** [comment] 2020-06-16 23:57
I believe just the access token, but take a look. Not sure what sengled has and will just with calls me make.

**Comment by mitchellross** [comment] 2020-06-17 00:17
Thanks. Very much appreciate the work you are doing on this.

2020-06-17 10:08:37 DEBUG (MainThread) [custom_components.sengledapi] 
-------------------------------------------------------------------
Sengled Bulb Home Assistant Integration

Version: v0.0.1
This is a custom integration
If you have any issues with this you need to open an issue here:

-------------------------------------------------------------------
2020-06-17 10:08:37 DEBUG (MainThread) [custom_components.sengledapi] Creating new SengledApi component
2020-06-17 10:08:37 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengledapi] Sengled Api initializing.
2020-06-17 10:08:37 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengledapi] Sengled Api initializing async.
2020-06-17 10:08:37 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengledapi] Sengled Api log in async.
2020-06-17 10:08:37 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengledapi] async_do_login_request - Sengled Api doing request.
2020-06-17 10:08:37 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengled_request] SengledApi: Sengled Request initializing.
2020-06-17 10:08:37 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengled_request] SengledApi: async_get_login_response Sengled Request getting response async.
2020-06-17 10:08:39 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengled_request] SengledApi: data from async_get_response {'ret': 0, 'msg': 'success', 'jsessionid': 'STRING REMOVED', 'appServerAddr': 'https://au-elements.cloud.sengled.com:9000/zigbee/', 'ucenterAddr': 'https://au-ucenter.cloud.sengled.com:9000/user/', 'gret': 0, 'serverVersionMin': '3', 'serverVersionNow': '3', 'nick_name': 'e-mail removed', 'user_id': ID removed}
2020-06-17 10:08:39 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengledapi] Sengled Api accessToken JSESSIONID=STRING REMOVED
2020-06-17 10:08:39 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengledapi] sengledapi async_initJSESSIONID=STRING REMOVED
2020-06-17 10:08:39 DEBUG (MainThread) [custom_components.sengledapi] SengledApi Connected to Sengled account
2020-06-17 10:08:39 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengledapi] Sengled Api getting devices.
2020-06-17 10:08:39 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengledapi] async_do_request - Sengled Api doing request.
2020-06-17 10:08:39 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengled_request] SengledApi: Sengled Request initializing.
2020-06-17 10:08:39 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengled_request] SengledApi: async_get_response Sengled Request getting response async.JSESSIONID=STRING REMOVED
2020-06-17 10:08:39 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengled_request] SengledApi: data from async_get_response {'messageCode': '200', 'info': 'OK', 'description': '正常', 'deviceInfos': [{'gatewayUuid': 'gateaway ID removed', 'gatewayName': 'Bedroom Hub', 'routerBssid': '00:00:00:00:00:00', 'activeTime': '2020-03-21 20:53:22', 'gatewayVersion': 'V4.3.9', 'gatewayIp': '192.168.1.92', 'isOnline': 1, 'ssid': 'Home', 'iterationCode': '2', 'category': 'element', 'gatewayProductCode': None, 'longitude': None, 'latitude': None, 'timeZone': 'Australia/Sydney', 'lampInfos': [{'deviceUuid': 'removed', 'deviceClass': 1, 'supportAttributes': '0,1,3,4', 'attributes': {'deviceRssi': '5', 'productCode': 'E1A-AC2', 'brightness': '255', 'activeTime': '2020-03-21 20:53:29', 'name': 'Mel bottom', 'colorMode': '3', 'isOnline': '1', 'version': '3', 'onCount': '482', 'typeCode': 'E1A-AC2', 'onoff': '1'}}, {'deviceUuid': 'removed', 'deviceClass': 1, 'supportAttributes': '0,1,3,4', 'attributes': {'deviceRssi': '5', 'productCode': 'E1A-AC2', 'brightness': '255', 'activeTime': '2020-03-21 20:53:29', 'name': 'Ross top', 'colorMode': '3', 'isOnline': '1', 'version': '3', 'onCount': '445', 'typeCode': 'E1A-AC2', 'onoff': '1'}}, {'deviceUuid': 'removed', 'deviceClass': 1, 'supportAttributes': '0,1,3,4', 'attributes': {'deviceRssi': '5', 'productCode': 'E1A-AC2', 'brightness': '255', 'activeTime': '2020-03-21 20:53:29', 'name': 'Ross bottom', 'colorMode': '3', 'isOnline': '1', 'version': '3', 'onCount': '484', 'typeCode': 'E1A-AC2', 'onoff': '1'}}, {'deviceUuid': 'removed', 'deviceClass': 1, 'supportAttributes': '0,1,3,4', 'attributes': {'deviceRssi': '5', 'productCode': 'E1A-AC2', 'brightness': '255', 'activeTime': '2020-03-21 20:53:29', 'name': 'Mel top', 'colorMode': '3', 'isOnline': '1', 'version': '3', 'onCount': '451', 'typeCode': 'E1A-AC2', 'onoff': '1'}}, {'deviceUuid': 'removed', 'deviceClass': 1, 'supportAttributes': '0,1,3,4', 'attributes': {'deviceRssi': '5', 'productCode': 'E1A-AC2', 'brightness': '127', 'activeTime': '2020-04-14 16:11:18', 'name': 'Window', 'colorMode': '', 'isOnline': '1', 'version': '3', 'onCount': '314', 'typeCode': 'E1A-AC2', 'onoff': '0'}}, {'deviceUuid': 'removed', 'deviceClass': 3, 'supportAttributes': '', 'attributes': {'deviceRssi': '1', 'productCode': 'E1E-G7F', 'activeTime': '2020-04-15 10:56:00', 'name': ' Smart Light Switch 1', 'colorMode': '', 'isOnline': '1', 'version': '9', 'onCount': '', 'typeCode': 'E1E-G7F', 'onoff': '1'}}, {'deviceUuid': 'removed', 'deviceClass': 1, 'supportAttributes': '0,1,3,4', 'attributes': {'deviceRssi': '5', 'productCode': 'E11-G23', 'brightness': '3', 'activeTime': '2020-04-17 10:42:12', 'name': 'Mel’s light', 'colorMode': '', 'isOnline': '1', 'version': '9', 'onCount': '108', 'typeCode': 'E11-G23', 'onoff': '0'}}, {'deviceUuid': 'removed', 'deviceClass': 1, 'supportAttributes': '0,1,3,4', 'attributes': {'deviceRssi': '5', 'productCode': 'E11-G23', 'brightness': '3', 'activeTime': '2020-04-17 10:50:16', 'name': 'Ross’s light', 'colorMode': '', 'isOnline': '1', 'version': '9', 'onCount': '142', 'typeCode': 'E11-G23', 'onoff': '0'}}, {'deviceUuid': 'removed', 'deviceClass': 1, 'supportAttributes': '0,1,3,4', 'attributes': {'deviceRssi': '5', 'productCode': 'E1A-AC2', 'brightness': '255', 'activeTime': '2020-04-25 19:34:22', 'name': 'Robe Bulb 1', 'colorMode': '', 'isOnline': '0', 'version': '3', 'onCount': '150', 'typeCode': 'E1A-AC2', 'onoff': '0'}}, {'deviceUuid': 'removed', 'deviceClass': 1, 'supportAttributes': '0,1,3,4', 'attributes': {'deviceRssi': '5', 'productCode': 'E1A-AC2', 'brightness': '255', 'activeTime': '2020-04-25 19:36:22', 'name': 'Robe Bulb 2', 'colorMode': '', 'isOnline': '0', 'version': '3', 'onCount': '147', 'typeCode': 'E1A-AC2', 'onoff': '0'}}, {'deviceUuid': 'removed', 'deviceClass': 1, 'supportAttributes': '0,1,3,4', 'attributes': {'deviceRssi': '5', 'productCode': 'E1A-AC2', 'brightness': '255', 'activeTime': '2020-04-25 19:37:53', 'name': 'Robe Bulb 3', 'colorMode': '', 'isOnline': '0', 'version': '3', 'onCount': '60', 'typeCode': 'E1A-AC2', 'onoff': '0'}}]}], 'success': True}
2020-06-17 10:08:39 DEBUG (MainThread) [custom_components.sengledapi] SengledApi Store the logged in account object for the platforms to use
2020-06-17 10:08:39 DEBUG (MainThread) [custom_components.sengledapi] SengledApi Start up lights, switch and binary sensor components
2020-06-17 10:08:40 DEBUG (MainThread) [custom_components.sengledapi.light] Creating new Sengled light component
2020-06-17 10:08:40 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengledapi] Sengled Api listing bulbs.
2020-06-17 10:08:40 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengledapi] Sengled Api getting devices.
2020-06-17 10:08:40 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengledapi] {'gatewayUuid': 'removed', 'gatewayName': 'Bedroom Hub', 'routerBssid': '00:00:00:00:00:00', 'activeTime': '2020-03-21 20:53:22', 'gatewayVersion': 'V4.3.9', 'gatewayIp': '192.168.1.92', 'isOnline': 1, 'ssid': 'Home', 'iterationCode': '2', 'category': 'element', 'gatewayProductCode': None, 'longitude': None, 'latitude': None, 'timeZone': 'Australia/Sydney', 'lampInfos': [{'deviceUuid': 'removed', 'deviceClass': 1, 'supportAttributes': '0,1,3,4', 'attributes': {'deviceRssi': '5', 'productCode': 'E1A-AC2', 'brightness': '255', 'activeTime': '2020-03-21 20:53:29', 'name': 'Mel bottom', 'colorMode': '3', 'isOnline': '1', 'version': '3', 'onCount': '482', 'typeCode': 'E1A-AC2', 'onoff': '1'}}, {'deviceUuid': 'removed', 'deviceClass': 1, 'supportAttributes': '0,1,3,4', 'attributes': {'deviceRssi': '5', 'productCode': 'E1A-AC2', 'brightness': '255', 'activeTime': '2020-03-21 20:53:29', 'name': 'Ross top', 'colorMode': '3', 'isOnline': '1', 'version': '3', 'onCount': '445', 'typeCode': 'E1A-AC2', 'onoff': '1'}}, {'deviceUuid': 'removed', 'deviceClass': 1, 'supportAttributes': '0,1,3,4', 'attributes': {'deviceRssi': '5', 'productCode': 'E1A-AC2', 'brightness': '255', 'activeTime': '2020-03-21 20:53:29', 'name': 'Ross bottom', 'colorMode': '3', 'isOnline': '1', 'version': '3', 'onCount': '484', 'typeCode': 'E1A-AC2', 'onoff': '1'}}, {'deviceUuid': 'removed', 'deviceClass': 1, 'supportAttributes': '0,1,3,4', 'attributes': {'deviceRssi': '5', 'productCode': 'E1A-AC2', 'brightness': '255', 'activeTime': '2020-03-21 20:53:29', 'name': 'Mel top', 'colorMode': '3', 'isOnline': '1', 'version': '3', 'onCount': '451', 'typeCode': 'E1A-AC2', 'onoff': '1'}}, {'deviceUuid': 'removed', 'deviceClass': 1, 'supportAttributes': '0,1,3,4', 'attributes': {'deviceRssi': '5', 'productCode': 'E1A-AC2', 'brightness': '127', 'activeTime': '2020-04-14 16:11:18', 'name': 'Window', 'colorMode': '', 'isOnline': '1', 'version': '3', 'onCount': '314', 'typeCode': 'E1A-AC2', 'onoff': '0'}}, {'deviceUuid': 'removed', 'deviceClass': 3, 'supportAttributes': '', 'attributes': {'deviceRssi': '1', 'productCode': 'E1E-G7F', 'activeTime': '2020-04-15 10:56:00', 'name': ' Smart Light Switch 1', 'colorMode': '', 'isOnline': '1', 'version': '9', 'onCount': '', 'typeCode': 'E1E-G7F', 'onoff': '1'}}, {'deviceUuid': 'removed', 'deviceClass': 1, 'supportAttributes': '0,1,3,4', 'attributes': {'deviceRssi': '5', 'productCode': 'E11-G23', 'brightness': '3', 'activeTime': '2020-04-17 10:42:12', 'name': 'Mel’s light', 'colorMode': '', 'isOnline': '1', 'version': '9', 'onCount': '108', 'typeCode': 'E11-G23', 'onoff': '0'}}, {'deviceUuid': 'removed', 'deviceClass': 1, 'supportAttributes': '0,1,3,4', 'attributes': {'deviceRssi': '5', 'productCode': 'E11-G23', 'brightness': '3', 'activeTime': '2020-04-17 10:50:16', 'name': 'Ross’s light', 'colorMode': '', 'isOnline': '1', 'version': '9', 'onCount': '142', 'typeCode': 'E11-G23', 'onoff': '0'}}, {'deviceUuid': 'removed', 'deviceClass': 1, 'supportAttributes': '0,1,3,4', 'attributes': {'deviceRssi': '5', 'productCode': 'E1A-AC2', 'brightness': '255', 'activeTime': '2020-04-25 19:34:22', 'name': 'Robe Bulb 1', 'colorMode': '', 'isOnline': '0', 'version': '3', 'onCount': '150', 'typeCode': 'E1A-AC2', 'onoff': '0'}}, {'deviceUuid': 'removed', 'deviceClass': 1, 'supportAttributes': '0,1,3,4', 'attributes': {'deviceRssi': '5', 'productCode': 'E1A-AC2', 'brightness': '255', 'activeTime': '2020-04-25 19:36:22', 'name': 'Robe Bulb 2', 'colorMode': '', 'isOnline': '0', 'version': '3', 'onCount': '147', 'typeCode': 'E1A-AC2', 'onoff': '0'}}, {'deviceUuid': 'removed', 'deviceClass': 1, 'supportAttributes': '0,1,3,4', 'attributes': {'deviceRssi': '5', 'productCode': 'E1A-AC2', 'brightness': '255', 'activeTime': '2020-04-25 19:37:53', 'name': 'Robe Bulb 3', 'colorMode': '', 'isOnline': '0', 'version': '3', 'onCount': '60', 'typeCode': 'E1A-AC2', 'onoff': '0'}}]}
2020-06-17 10:08:40 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengled_bulb] SengledApi: Light Mel bottom initializing.JSESSIONID=STRING REMOVED
2020-06-17 10:08:40 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengled_bulb] SengledApi: Light Ross top initializing.JSESSIONID=STRING REMOVED
2020-06-17 10:08:40 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengled_bulb] SengledApi: Light Ross bottom initializing.JSESSIONID=STRING REMOVED
2020-06-17 10:08:40 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengled_bulb] SengledApi: Light Mel top initializing.JSESSIONID=STRING REMOVED
2020-06-17 10:08:40 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengled_bulb] SengledApi: Light Window initializing.JSESSIONID=STRING REMOVED
2020-06-17 10:08:40 ERROR (MainThread) [homeassistant.components.light] Error while setting up sengledapi platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 178, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/sengledapi/light.py", line 33, in async_setup_platform
    for light in await hass.data[DOMAIN]["sengledapi_account"].async_list_bulbs()
  File "/config/custom_components/sengledapi/sengledapi/sengledapi.py", line 86, in async_list_bulbs
    device["attributes"]["brightness"],
KeyError: 'brightness'

**Comment by jfarmer08** [comment] 2020-06-17 01:04
@mitchellross Well i see the issue.  I am not sure what this device is, but the problem is it does not support brightness. Since i don't have it will be hard to support this. I will create a fix so the sengledAPI can ignore it. Then maybe add it back later if i can. Could be put a list togather of what devices you have on sengled App? It would help in the feature.

```
      {
         "deviceUuid":"removed",
         "deviceClass":3,
         "supportAttributes":"",
         "attributes":{
            "deviceRssi":"1",
            "productCode":"E1E-G7F",
            "activeTime":"2020-04-15 10:56:00",
            "name":" Smart Light Switch 1",
            "colorMode":"",
            "isOnline":"1",
            "version":"9",
            "onCount":"",
            "typeCode":"E1E-G7F",
            "onoff":"1"
         }
```

**Comment by mitchellross** [comment] 2020-06-17 01:19
Aha! It's the light switch. It's just a switch - so ignoring it is the right approach. I only have two other types of lights - 8 element downlights and two element bulbs.

**Comment by jfarmer08** [comment] 2020-06-17 01:44
I have update the repo. If you update hopefully things will be in order.

**Comment by mitchellross** [comment] 2020-06-17 02:51
Brilliant. We can close this one. I'm going to open another one as the log is reporting different issues.

**Comment by jfarmer08** [comment] 2020-06-17 22:35
Did you get this figured out?

**Comment by mitchellross** [comment] 2020-06-17 22:53
Thanks for checking in. I'm doing a fresh install. And I'm going to set up a singled hub with  only one light. I'll report back with logs of anything I find. I couldn't control any of my normal 10 lights yesterday - the state was reporting fine, but just couldn't change it. So I'm going to simplify and see if I can replicate in a clean install.

**Comment by jfarmer08** [comment] 2020-06-18 01:26
More than likely they are using a different api call then the US version. Just let me know what errors you get and maybe we can work them out.

**Comment by mitchellross** [comment] 2020-06-18 08:15
Awesome - thanks again for your help. I've done a fresh install and I've got a test hub set up with only one single bulb attached. That makes the logs slightly less crazy to read. 

As I think the logs show, I try to turn the light on and off - but nothing happens. 

[home-assistant_upload.log](https://github.com/jfarmer08/ha-sengledapi/files/4797213/home-assistant_upload.log)

**Comment by mitchellross** [comment] 2020-06-18 10:11
Lol - as easy as turning the "US" to an "AU" in the sengled_request.py file. That much I can do. What I can't do is script it so it makes that choice without user intervention...

But wow - this is great. It's really responsive.

**Comment by jfarmer08** [comment] 2020-06-18 11:11
Can you tell me what you changed for it work on your end.

**Comment by jfarmer08** [comment] 2020-06-18 11:22
I would think the sengled_bulb.py would have changed but just want to make sure.

**Comment by mitchellross** [comment] 2020-06-18 11:56
Sorry - yes should have been specific. There's three reference to "US" that I changed to "AU" in sengled_bulb.py

"https://**au**-elements.cloud.sengled.com/zigbee/device/deviceSetOnOff.json"

I'm still getting a few of these lines that also occurred in the debug log above - is this anything to worry about?

2020-06-18 21:19:05 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sengledapi doing I/O at custom_components/sengledapi/sengledapi/sengled_request.py, line 34: r = requests.post(self._url, headers=self._header, data=self._payload)

**Comment by jfarmer08** [comment] 2020-06-18 12:20
No that should not cause any issues. HA is is warning you. I will fix this in a later release. Thanks for the update.

**Comment by mitchellross** [comment] 2020-06-18 12:43
Thanks very much for your work on this – it’s great.

**Comment by jfarmer08** [comment] 2020-06-18 15:50
@mitchellross I have released a new update to address the issues you seen. You will need to change your configuration by adding in country: au. Also I have added in support for your switch, but i am not sure it will work. So if you update and have issues or it just works please let me know. 
```
sengledapi:
  username: <email for sengled>
  password: <password for sengled>
  country: <country>
```

**Closed by jfarmer08** 2020-06-18 15:50 UTC
Labels: bug
